const registry = {
  check: () => import('~/assets/icons/check.svg?react'),
  cross: () => import('~/assets/icons/cross.svg?react'),
  curvedArrow: () => import('~/assets/icons/curved-arrow.svg?react'),
  dragAndDrop: () => import('~/assets/icons/drag-and-drop.svg?react'),
  error: () => import('~/assets/icons/error.svg?react'),
  fileExplorer: () => import('~/assets/icons/file-explorer.svg?react'),
  github: () => import('~/assets/icons/github.svg?react'),
  info: () => import('~/assets/icons/info.svg?react'),
  laptop: () => import('~/assets/icons/laptop.svg?react'),
  link: () => import('~/assets/icons/link.svg?react'),
  lock: () => import('~/assets/icons/lock.svg?react'),
  logo: () => import('~/assets/icons/logo.svg?react'),
  lowResHeart: () => import('~/assets/icons/low-res-heart.svg?react'),
  mobile: () => import('~/assets/icons/mobile.svg?react'),
  moon: () => import('~/assets/icons/moon.svg?react'),
  play: () => import('~/assets/icons/play.svg?react'),
  question: () => import('~/assets/icons/question.svg?react'),
  redo: () => import('~/assets/icons/redo.svg?react'),
  save: () => import('~/assets/icons/save.svg?react'),
  setting: () => import('~/assets/icons/setting.svg?react'),
  star: () => import('~/assets/icons/star.svg?react'),
  sun: () => import('~/assets/icons/sun.svg?react'),
  tick: () => import('~/assets/icons/tick.svg?react'),
  trash: () => import('~/assets/icons/trash.svg?react'),
  videoFile: () => import('~/assets/icons/video-file.svg?react'),
  warning: () => import('~/assets/icons/warning.svg?react'),
} as const

export default registry
